const routes = {
  Auth: 'Auth',
  OTP: 'OTP',
  Login: 'Login',
  CreatePIN: 'CreatePIN',
  CreateFakePIN: 'CreateFakePIN',
  ChangePIN: 'ChangePIN',
  ChangeFakePIN: 'ChangeFakePIN',
  Dashboard: 'Dashboard',
  Sms: 'Sms',
  SmsList: 'SmsList',
  SmsChat: 'SmsChat',
  PhoneBook: 'PhoneBook',
  Comments: 'Comments',
  Mail: 'Mail',
  MailList: 'MailList',
  MailView: 'MailView',
  MailBook: 'MailBook',
  Tag: 'Tag',
  Settings: 'Settings',
  Profile: 'Profile',
  Security: 'Security',
  Theme: 'Theme',
  Language: 'Language',
  About: 'About',
  Open: 'Open',
  Order: 'Order',
  Done: 'Done',
};
export default routes;
